# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-03-18 22:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('letswatch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='url',
            new_name='trailer',
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default=datetime.datetime(2019, 3, 18, 22, 50, 28, 227635, tzinfo=utc), upload_to='movie_thumb'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='picture',
            field=models.ImageField(default='profile_images/default.png', upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='movie',
            name='thumb',
            field=models.ImageField(blank=True, upload_to='movies'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='profile_images/default.png', upload_to='profile_images'),
        ),
    ]
