# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-03-19 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letswatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='letswatch.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='letswatch.UserProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='VideoPost',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set([('user', 'movie')]),
        ),
    ]
