# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-03-18 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letswatch', '0002_auto_20190318_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='picture',
            field=models.ImageField(blank=True, default='profile_images/default.png', upload_to='movies'),
        ),
    ]
