# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-03-19 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letswatch', '0002_auto_20190319_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='profile_images/default.png', upload_to='profile_images/'),
        ),
    ]
