# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-03-17 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letswatch', '0002_auto_20190316_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='VideoPost',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='VideoPost',
        ),
    ]
