# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-03-18 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letswatch', '0003_auto_20190318_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='picture',
            field=models.ImageField(upload_to='movies'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumb',
            field=models.ImageField(upload_to='movies'),
        ),
    ]
