# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-03-20 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letswatch', '0003_auto_20190319_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images/'),
        ),
    ]
