# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-03-18 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letswatch', '0002_auto_20190318_2250'),
        ('letswatch', '0005_auto_20190318_0256'),
    ]

    operations = [
    ]
