# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-03-18 23:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('letswatch', '0006_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='trailer',
        ),
        migrations.AddField(
            model_name='movie',
            name='url',
            field=models.URLField(default=datetime.datetime(2019, 3, 18, 23, 22, 22, 276845, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letswatch.Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='picture',
            field=models.ImageField(upload_to='movies2/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumb',
            field=models.ImageField(upload_to='movies2/'),
        ),
    ]
