# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-03-20 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letswatch', '0006_auto_20190320_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='url',
        ),
    ]
