# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-03-18 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letswatch', '0006_auto_20190318_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name_plural': 'Movies'},
        ),
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default='-', unique=True),
            preserve_default=False,
        ),
    ]
