# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-03-18 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letswatch', '0007_auto_20190318_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(),
        ),
    ]
