# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-03-20 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letswatch', '0007_remove_movie_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='url',
            field=models.CharField(default='https://www.google.com', max_length=200),
            preserve_default=False,
        ),
    ]
