# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-03-20 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letswatch', '0009_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.TextField(blank=True),
        ),
    ]
