# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-03-20 12:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('letswatch', '0009_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(default=datetime.datetime(2019, 3, 20, 12, 21, 0, 747698, tzinfo=utc), max_length=350),
            preserve_default=False,
        ),
    ]
