# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-03-20 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letswatch', '0011_auto_20190320_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=600),
        ),
    ]
