# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-03-20 23:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('letswatch', '0013_auto_20190320_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date',
        ),
        migrations.AddField(
            model_name='review',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 20, 23, 57, 49, 264291, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
    ]
