# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-03-21 02:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letswatch', '0014_auto_20190320_2357'),
        ('letswatch', '0013_auto_20190320_2112'),
    ]

    operations = [
    ]
